---
apiVersion: v1
kind: Pod
metadata: 
  name: postgres
  labels: 
    name: postgres
spec: 
  containers: 
    - name: postgres
      image: postgres
      ports: 
        - containerPort: 5432
      env: 
       - name: POSTGRES_PASSWORD
         value: admin 
       - name: POSTGRES_USER
         value: myuser
       - name: POSTGRES_DB
         value: mydb
...
